var assert=require("assert")
describe('google search', () => {
    it('should have the correct title',  () => {
         browser.url("http://newtours.demoaut.com")
         $('[name=userName]').setValue("kalptest")
         $('[name=password]').setValue("kalptest")
         $("[name=login]").click()
        browser.url('http://newtours.demoaut.com/mercuryreservation.php')
        const trip=  $('//*[@value="oneway"]')
        trip.click()
        $("[name=passCount]").click()
        const noofpersons=  $('//*[@value="2"]')
        noofpersons.click()
        $("[name=fromPort]").click()
        const formadd=  $('//*[@value="London"]')
        formadd.click()
        $("[name=fromMonth]").click()
        const frommonth=  $('//*[@value="5"]')
        frommonth.click()
         $("[name=fromDay]").click()
        const fromdate=  $('//*[@value="12"]')
        fromdate.click()
        $("[name=toPort]").click()
        const toadd=  $('//*[@value="Paris"]')
        toadd.click()
        $("[name=toMonth]").click()
        const tomonth=  $('//*[@value="7"]')
        tomonth.click()
         $("[name=toDay]").click()
        const todate=  $('//*[@value="2"]')
        todate.click()
        const serviceclass=  $('//*[@value="First"]')
        serviceclass.click()
        $("[name=airline]").click()
        const airline=  $('//*[text()="Pangea Airlines"]')
        airline.click()
        $("[name=findFlights]").click();
        browser.url("http://newtours.demoaut.com/mercurypurchase.php")
        $("[name=creditCard]").click()
        const card=  $('//*[text()="Visa"]')
        card.click()
        $('[name=creditnumber]').setValue("12312323421124")
        $("[name=cc_exp_dt_mn]").click()
        const cardmonth=  $('//option[contains(text(),"04")]')
        cardmonth.click()
        $("[name=cc_exp_dt_yr]").click()
        const cardyear=  $('//option[contains(text(),"2008")]')
        cardyear.click()
        $('[name=cc_frst_name]').setValue("bavana")
         $('[name=cc_mid_name]').setValue("redyd")
         $('[name=cc_last_name]').setValue("poloi")
         
         $("[name=buyFlights]").click();
         const logout=  $('/html/body/div/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr[1]/td[2]/table/tbody/tr[7]/td/table//tr/td[3]/a[@href="mercurysignoff.php"]/img[@src="/images/forms/Logout.gif"]')
         browser.url("http://newtours.demoaut.com")





    })
})